# このconfigは、 dockerでMisskey本体を起動せず、 redisとpostgresql などだけを起動します

services:
  redis:
    restart: always
    image: valkey/valkey:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 5s
      retries: 20

  postgres:
    restart: always
    image: groonga/pgroonga:latest-alpine-17
    ports:
      - "5432:5432"
    # environment:
    #   POSTGRES_USER: USER_HERE
    #   POSTGRES_PASSWORD: PASSWORD_HERE
    #   POSTGRES_DB: DB_HERE
    env_file:
      - .config/docker.env
    volumes:
      - ./postgres:/var/lib/postgresql/data
    healthcheck:
      test: "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"
      interval: 5s
      retries: 20

#  meilisearch:
#    restart: always
#    image: getmeili/meilisearch:v1.3.4
#    environment:
#      - MEILI_NO_ANALYTICS=true
#      - MEILI_ENV=production
#    env_file:
#      - .config/meilisearch.env
#    volumes:
#      - ./meili_data:/meili_data

#  translator:
#    restart: always
#    image: libretranslate/libretranslate:latest
#    healthcheck:
#    test: ['CMD-SHELL', './venv/bin/python scripts/healthcheck.py']

